[tool.poetry]
name = "aider-vertex"
version = "0.69.2"
description = "Aider with Vertex AI support"
authors = ["Andrey Stepantsov"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
aider-chat = "*"
google-cloud-aiplatform = "*"
anthropic = { extras = ["vertex"], version = "*" }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
